# Minimal example with TensorFlow 2.0
In this notebook we will recreate our machine learning algorithm using TF 2.0.

## Import the relevant libraries

In [1]:
# We must always import the relevant libraries for our problem at hand. NumPy and TensorFlow are required for this example.
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

## Data generation

We generate data using the exact same logic and code as the example from the previous notebook. The only difference now is that we save it to an npz file. Npz is numpy's file type which allows you to save numpy arrays into a single .npz file. We introduce this change because in machine learning most often: 

* you are given some data (csv, database, etc.)
* you preprocess it into a desired format (later on we will see methods for preprocesing)
* you save it into npz files (if you're working in Python) to access later

Nothing to worry about - this is literally saving your NumPy arrays into a file that you can later access, nothing more.

In [2]:
# First, we should declare a variable containing the size of the training set we want to generate.
observations = 1000

# We will work with two variables as inputs. You can think about them as x1 and x2 in our previous examples.
# We have picked x and z, since it is easier to differentiate them.
# We generate them randomly, drawing from an uniform distribution. There are 3 arguments of this method (low, high, size).
# The size of xs and zs is observations x 1. In this case: 1000 x 1.
xs = np.random.uniform(low=-10, high=10, size=(observations,1))
zs = np.random.uniform(-10, 10, (observations,1))

# Combine the two dimensions of the input into one input matrix. 
# This is the X matrix from the linear model y = x*w + b.
# column_stack is a Numpy method, which combines two matrices (vectors) into one.
generated_inputs = np.column_stack((xs,zs))

# We add a random small noise to the function i.e. f(x,z) = 2x - 3z + 5 + <small noise>
noise = np.random.uniform(-1, 1, (observations,1))

# Produce the targets according to our f(x,z) = 2x - 3z + 5 + noise definition.
# In this way, we are basically saying: the weights should be 2 and -3, while the bias is 5.
generated_targets = 2*xs - 3*zs + 5 + noise

# save into an npz file called "TF_intro"
np.savez('TF_intro', inputs=generated_inputs, targets=generated_targets)

## Solving with TensorFlow

<i/>Note: This intro is just the basics of TensorFlow which has way more capabilities and depth than that.<i>

In [3]:
# Load the training data from the NPZ
training_data = np.load('TF_intro.npz')

In [4]:
# Declare a variable where we will store the input size of our model
# It should be equal to the number of variables you have
input_size = 2
# Declare the output size of the model
# It should be equal to the number of outputs you've got (for regressions that's usually 1)
output_size = 1

# Outline the model
# We lay out the model in 'Sequential'
# Note that there are no calculations involved - we are just describing our network
model = tf.keras.Sequential([
                            # Each 'layer' is listed here
                            # The method 'Dense' indicates, our mathematical operation to be (xw + b)
                            tf.keras.layers.Dense(output_size,
                                                 # there are extra arguments you can include to customize your model
                                                 # in our case we are just trying to create a solution that is 
                                                 # as close as possible to our NumPy model
                                                 kernel_initializer=tf.random_uniform_initializer(minval=-0.1, maxval=0.1),
                                                 bias_initializer=tf.random_uniform_initializer(minval=-0.1, maxval=0.1)
                                                 )
                            ])

# We can also define a custom optimizer, where we can specify the learning rate
custom_optimizer = tf.keras.optimizers.SGD(learning_rate=0.02)
# Note that sometimes you may also need a custom loss function 
# That's much harder to implement and won't be covered in this course though

# 'compile' is the place where you select and indicate the optimizers and the loss
model.compile(optimizer=custom_optimizer, loss='mean_squared_error')

# finally we fit the model, indicating the inputs and targets
# if they are not otherwise specified the number of epochs will be 1 (a single epoch of training), 
# so the number of epochs is 'kind of' mandatory, too
# we can play around with verbose; we prefer verbose=2
model.fit(training_data['inputs'], training_data['targets'], epochs=100, verbose=2)

Epoch 1/100
32/32 - 0s - loss: 35.4724 - 466ms/epoch - 15ms/step
Epoch 2/100
32/32 - 0s - loss: 1.2758 - 52ms/epoch - 2ms/step
Epoch 3/100
32/32 - 0s - loss: 0.4464 - 52ms/epoch - 2ms/step
Epoch 4/100
32/32 - 0s - loss: 0.3920 - 45ms/epoch - 1ms/step
Epoch 5/100
32/32 - 0s - loss: 0.4179 - 50ms/epoch - 2ms/step
Epoch 6/100
32/32 - 0s - loss: 0.4040 - 47ms/epoch - 1ms/step
Epoch 7/100
32/32 - 0s - loss: 0.4194 - 54ms/epoch - 2ms/step
Epoch 8/100
32/32 - 0s - loss: 0.4206 - 46ms/epoch - 1ms/step
Epoch 9/100
32/32 - 0s - loss: 0.3866 - 54ms/epoch - 2ms/step
Epoch 10/100
32/32 - 0s - loss: 0.4112 - 44ms/epoch - 1ms/step
Epoch 11/100
32/32 - 0s - loss: 0.4135 - 47ms/epoch - 1ms/step
Epoch 12/100
32/32 - 0s - loss: 0.3976 - 43ms/epoch - 1ms/step
Epoch 13/100
32/32 - 0s - loss: 0.4000 - 42ms/epoch - 1ms/step
Epoch 14/100
32/32 - 0s - loss: 0.4007 - 45ms/epoch - 1ms/step
Epoch 15/100
32/32 - 0s - loss: 0.3914 - 41ms/epoch - 1ms/step
Epoch 16/100
32/32 - 0s - loss: 0.4193 - 42ms/epoch - 1ms/ste

## Extract the weights and bias
Extracting the weight(s) and bias(es) of a model is not an essential step for the machine learning process. In fact, usually they would not tell us much in a deep learning context. However, this simple example was set up in a way, which allows us to verify if the answers we get are correct.

In [5]:
# Extracting the weights and biases is achieved quite easily
model.layers[0].get_weights()

[array([[ 1.9806088],
        [-3.0671813]], dtype=float32),
 array([4.9634194], dtype=float32)]

In [6]:
# We can save the weights and biases in separate variables for easier examination
# Note that there can be hundreds or thousands of them!
weights = model.layers[0].get_weights()[0]
weights

array([[ 1.9806088],
       [-3.0671813]], dtype=float32)

In [7]:
# We can save the weights and biases in separate variables for easier examination
# Note that there can be hundreds or thousands of them!
bias = model.layers[0].get_weights()[1]
bias

array([4.9634194], dtype=float32)

## Extract the outputs (make predictions)
Once more, this is not an essential step, however, we usually want to be able to make predictions.

In [8]:
# We can predict new values in order to actually make use of the model
# Sometimes it is useful to round the values to be able to read the output
# Usually we use this method on NEW DATA, rather than our original training data
model.predict_on_batch(training_data['inputs']).round(1)

array([[ -4.4],
       [ 12. ],
       [ 37.3],
       [ 50.7],
       [ 28.4],
       [ 12.8],
       [ 28.8],
       [-28.7],
       [  1.7],
       [-10.3],
       [ -3.2],
       [ 19.8],
       [ 11.6],
       [ -5.2],
       [ -4.1],
       [ 29.9],
       [ 32.4],
       [  9.9],
       [ 27.2],
       [  6.1],
       [ -6.8],
       [ 31.7],
       [-16.3],
       [ -5.8],
       [  6.9],
       [ -7.1],
       [ 14.2],
       [-19.2],
       [ 33.6],
       [ -3.3],
       [-11.8],
       [ -0.8],
       [  8.4],
       [ -4.3],
       [ 30.4],
       [  9.6],
       [ -5.7],
       [ 28.1],
       [ -3.8],
       [-30. ],
       [  5.6],
       [ 27.3],
       [ 18. ],
       [ 17.1],
       [ 17.8],
       [-21.5],
       [  4.4],
       [-17. ],
       [ 53.2],
       [ 12.5],
       [-13. ],
       [ 12.1],
       [ 11. ],
       [ -2. ],
       [ 43.7],
       [-21.8],
       [-34. ],
       [ 25.2],
       [-11.3],
       [-15.6],
       [-29.1],
       [  8.4],
       [

In [9]:
# If we display our targets (actual observed values), we can manually compare the outputs and the targets
training_data['targets'].round(1)

array([[ -3.8],
       [ 11.6],
       [ 37.5],
       [ 50.1],
       [ 28.6],
       [ 12.3],
       [ 28.4],
       [-29.1],
       [  3. ],
       [-11.1],
       [ -3.4],
       [ 19.7],
       [ 11.5],
       [ -5.2],
       [ -4.4],
       [ 29.8],
       [ 31.4],
       [  9.7],
       [ 27. ],
       [  6.9],
       [ -6.1],
       [ 30.7],
       [-15.7],
       [ -4.9],
       [  6.1],
       [ -6.3],
       [ 12.9],
       [-20. ],
       [ 33.9],
       [ -3.2],
       [-11.7],
       [ -1.8],
       [  7.7],
       [ -4.8],
       [ 30.7],
       [  9.8],
       [ -5.8],
       [ 27.7],
       [ -4.1],
       [-30.2],
       [  6.5],
       [ 26.8],
       [ 18.8],
       [ 16.4],
       [ 17.8],
       [-20.9],
       [  4.3],
       [-16.8],
       [ 53.7],
       [ 12.6],
       [-11.7],
       [ 13.4],
       [ 10.5],
       [ -3.2],
       [ 43.9],
       [-22.6],
       [-32.4],
       [ 25.1],
       [-10.8],
       [-15.3],
       [-28.6],
       [  8.6],
       [

## Plotting the data

In [ ]:
# The model is optimized, so the outputs are calculated based on the last form of the model

# We have to np.squeeze the arrays in order to fit them to what the plot function expects.
# Doesn't change anything as we cut dimensions of size 1 - just a technicality.
plt.plot(np.squeeze(model.predict_on_batch(training_data['inputs'])), np.squeeze(training_data['targets']))
plt.xlabel('outputs')
plt.ylabel('targets')
plt.show()

# Voila - what you see should be exactly the same as in the previous notebook!
# You probably don't see the point of TensorFlow now - it took us the same number of lines of code
# to achieve this simple result. However, once we go deeper in the next chapter,
# TensorFlow will save us hundreds of lines of code.